### ISSUE TITLE
RSpec 3 compatibility

### ISSUE THREAD

**Issue by liveh2o** [localshred/protobuf-rspec#11]
Currently, Protobuf::RSpec is locking RSpec to ~> 2.6. We need to see what needs to be done to make this compatible with RSpec 3.

**Comment by mmmries** [comment]
I just pulled down a local copy of this and bumped the rspec dependency to `~> 3.0` and my whole test suite looked fine. I don't think we were using anything specific to rspec 2 in this gem.

I think we should just update the rspec dependency to `>= 2.1 < 4.0` so that we aren't trying to predict the future of rspec. Then bump the gem version to `1.1.0` and release an update.

@localshred does that sound like a reasonable plan to you?

**Comment by liveh2o** [comment]
OK, I've just rolled [v1.1.0.alpha](https://github.com/localshred/protobuf-rspec/releases/tag/v1.1.0.alpha) which has a dependency on RSpec 3.x. @mmmries, can you try it out and see if things still work as expected?

**Comment by mmmries** [comment]
`1.1.0.alpha` worked fine for me. Do we not care about letting it continue to support RSpec 2.X as well as 3.X? I don't see any reason to drop support for 2.X since this is not really using any private APIs and it seems to work fine on both major versions.

**Comment by liveh2o** [comment]
OK, released [v1.1.0](https://github.com/localshred/protobuf-rspec/releases/tag/v1.1.0) stable with support for RSpec 2.8–3.x.
